apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Binding
metadata:
  name: mysqlbinding-test-24
  namespace: default
spec:
  instanceRef:
    name: mysql-test-11
  secretName: dbsecret-1
  parameters:
    instance:  mysqlbinding-test-24
    namespace: default
    instanceLabel: mysqlbinding